### PR TITLE
Fix init layout

### LINKED ISSUE #66: Fix initLayout
You should use the ExpandableLinearLayout if child views may change a size. 
For example, it gets and sets values after connection.
The ExpandableRelativeLayout isn't supported in the above.

```java
child.setText("Sets text from a server");
expandableLayout.initLayout(true);``// Recalculate size of children
```

`initLayout()` is deprecated in v1.5.0.
The argument of `isMaintain`  doesn't work.

### LINKED ISSUE #84: ExpandableLinearLayout does not work as expected after adding view programatically
ExpandableLinearLayout does not work after adding view programatically

If Programatically we would call : 
`getLayoutInflater().inflate(R.layout.partial, expandable, true);`
then Expanding will not work properly.

If **using** `expandable.initLayout(true);` then there are 2 cases:

1. If Layout is collapsed during inflate and calling **initLayout** - Expand will not work at all
2. If Layout is expanded during inflate and calling **initLayout**  - Expand will work, but last item will not be visibile. This is caused by `getMeasuredHeight() == 0`

If **not using** `expandable.initLayout(true);` then last item is also not visible. (due the `isCalculatedSize == true`)

### PR DESCRIPTION
**Pull request by AAkira**
You have to call `ExpandableLinarLayout.initLayout()` if container size is changed.
- Notice
  `ExpandableRelativeLayout` doesn't have this method.
  You should use the ExpandableLinearLayout if container size is changed.

Fix #84
Close #66

### CODE REVIEW

**Comment by expilu** [comment]
When will version 1.6.0 with this fix be released?

**Comment by AAkira** [comment]
@expilu
I'm sorry for the delay.
I released 1.6.0 now, please check it.

**Comment by expilu** [comment]
It works perfect now. Thanks!  ;)

**Comment by hshahdoost** [comment]
Is there a reason for `initLayout` only existing in `ExpandableLinearLayout` and not in `ExpandableRelativeLayout`?

**Pull request merged**
