### PR TITLE
Fix recycler view expanse

### LINKED ISSUE #71: ExpandableLinearLayout & ExpandableRelativeLayout  height issue when recycling item in RecyclerView
When scrolling a list with a lot of elements I expand one ExpandableLinearLayout then scroll again to another element where ExpandableLinearLayout is supposed to expand even more, but sadly it's reusing the same view and does not expand fully.

How can I force a new height calculation?

### LINKED ISSUE #76: List view inside Expandable Linear Layout Not working
I have used a Expandable Linear Layout in recycler view and List view inside expandable layout but the list scroll isnt working and dynamic change of height has been a issue

### PR DESCRIPTION
**Pull request by AAkira**
You have to set `holder.expandableLayout.setInRecyclerView(true);` and `holder.setIsRecyclable(false);` if it's used in recycler view.

Notice :  A recycler view isn't recycled if you set a `holder.setIsRecyclable(false);`.

Fix #71
Fix #76

### CODE REVIEW

**Comment by abunayem** [comment]
i can't set holder.expandableLayout.setInRecyclerView(true); android studio show it is wrong!

**Comment by masoudslipknot** [comment]
hi ! tnx for your library . i want to add a recyclerview inside my expandable layout . and i want to have this expandable layout in a another recyclerview is this possible ?  i mean we have only one activity . and we have items of kind expandable layouts  in a recyclerview . now i want to when clicking in expandable layout it shows another recyclerview .

**Comment by osmer** [comment]
Hi @AAkira I have this in my gradle file:
compile 'com.github.aakira:expandable-layout:1.6.0@aar'

so, I tried to add 
detailsLayout.setInRecyclerView(true);

But I got: Cannot Resolve method setInRecyclerView(boolean)

On Android Studio. Please help. Thanks

**Comment by dzalif** [comment]
holder.expandableLayout.setInRecyclerView(true); not working. There is no method on that.

**Pull request merged**
